#!/usr/bin/env perl
# list of images used by lacrosse; defaults to all
# --build lists only ones we build
# --notbuild lists only ones we don't build
# --sync lists only ones to sync across cluster

use Getopt::Long;

my $build, $notbuild, $sync;
GetOptions("build" => \$build,
	   "notbuild" => \$notbuild,
	   "sync" => \$sync,
	) or die ("Error in command line arguments\n");

# manually configured data: first array entry is build-p, second is sync-p
$images{"neo-fuzz-ccl"}=[1,1];

# Currently tools/start-pereti uses the 'pereti' image below.
# Lisp also uses the 'pereti' image. The 'pereti' image is built FROM
# the 'pereti-automation:v3' image at the time of this commit.
#
# We should probably conjoin the two and use only 'pereti' BUT as of this
# writing I (pkeller) don't know how GT updates the pereti installation
# and we may have kept it separate for that reason. Ask DJM.

## DJM pereti unavail, commenting these out for now
#$images{"pereti-automation"}=[0,0];	# pereti, below, includes this (although currently FROM p-a:v3 not :latest)
#$images{"pereti"}=[1,1];

# DJM Tue Oct 22 11:13:56 CDT 2019 peach now in neo-fuzz-ccl; see start-peach
#$images{"peach"}=[1,0];
$images{"driller"}=[1,1];
#$images{"chisel"}=[1,0];
#$images{"confine"}=[1,0];
#$images{"firmadyne"}=[1,0];
#$images{"fuzzball"}=[1,0];	# NOTE currently not syncing fball, but someday we will probably want to
#$images{"whatclib"}=[1,1];
#$images{"whatclib-build"}=[0,0];	# FIXME i'm not sure what we should do w/ these.
$images{"langchain"}=[1,1];
$images{"lacrosse-utils"}=[1,1];
for $img (keys(%images)) {
  if ( ($build && $images{$img}[0]) || ($notbuild && !$images{$img}[0]) || ($sync && $images{$img}[1]) || (!$build && !$sync &&!$notbuild) ) {
	print "$img\n"
	}
}
