#!/bin/bash
# This scripts exists b/c getting prt to run the right pattern of stuff is hard.
# This is what we want, but it doesnt work via prt directly, fwr
#command      => [ "../tools/dupl-template", "<../crs-sandbox-items/template-for-compose", ">../../../compose.yaml" ],
set -e

thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd -P "$( dirname "$SOURCE" )" && pwd )"

#PROGNAME=$(basename "$0")
#warn()  { echo "$PROGNAME: ${@}" 1>&2; }
#die()   { warn "${@}"; exit 1; }
#dbug()   { test -z $DEBUG || warn "${@}"; }

$thisdir/dupl-template $1 $2 <$thisdir/../crs-sandbox-items/template-for-compose > $thisdir/../../../compose.yaml
#dupl-ovverides doesn't care about AT_SIFT, ignoring $1
$thisdir/dupl-overrides $2 <$thisdir/../crs-sandbox-items/template-for-overrides > $thisdir/../../../compose_local_overrides.yaml
