#!/bin/bash

# Setup access to user's personal docker daemon
# including loopback on 10.0.2.2
systemctl --user set-environment DOCKERD_ROOTLESS_ROOTLESSKIT_ALLOW_HOST_LOOPBACK=true
eval "$(docker-rootless-init)"
#dbug DOCKER_HOST is $DOCKER_HOST
