---
exclude: >
  (?x)(
      dind_cache|
      dind_cache/*|
      crs_scratch|
      crs_scratch/*|
      cp_root|
      cp_root/*|
      crs/*
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 454ade935bffb366ae7d968c49be309f1041d747
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: ['--branch', 'main']

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
      - id: shellcheck

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--strict, -c=.github/linters/.yamllint]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: ['--config', '.github/linters/.markdown-lint']

  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.27
    hooks:
      - id: actionlint
        args: ['-config-file', '.github/linters/actionlint.yaml']
