---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: crs
resources:
  - ../base

patches:
  - path: crs-scratch-pvc.yaml
  - path: cp-root-pvc.yaml
  - path: crs-env.yaml
