---
# Applied in vcluster template, not included in competition kustomization. Here for reference
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crs-cluster-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["nodes/stats"]
    verbs: ["get"]
