IMAGE=langchain
include ../common/Makefile-header

COMMON_FILE_PATHS = $(addprefix ../common/, ${COMMON_FILES}) ../../langchain/pyproject.toml ../../langchain/poetry.lock

include ../common/Makefile-body
