# COMPETITORS: You may use this GitHub action file for assisting your development

name: CRS Action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  crs-action:
    runs-on:
      group: large-runners
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Do Nothing
        run: |
          echo "This is a sample action that competitors can replace to assist development."
