name: Create and publish a Docker images for the CRS
permissions: read-all
# Configures this workflow to run every time a release is published
on:
  release:
    types: [published]

# There is a single job in this workflow.
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      is_template_repo: ${{ steps.check-repo.outputs.is_template_repo }}
    steps:
        - name: Check if this is the source (template) repository
          id: check-repo
          run: |
            if [ "${{ github.repository }}" == "aixcc-sc/crs-sandbox" ]; then
              echo "This repo is the template repo..."
              echo "is_template_repo=true" >> "$GITHUB_OUTPUT"
              exit 0
            fi
            echo "is_template_repo=false" >> "$GITHUB_OUTPUT"

  build-and-push-image:
    needs: check
    runs-on:
      group: large-runners
    if: ${{ needs.check.outputs.is_template_repo == 'true' }}
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    strategy:
      fail-fast: false
      matrix:
        # COMPETITORS: Update this list of docker files to include all images needed for your CRS
        # These images will be copied into your CRS execution environment at competition time
        # REMINDER: A CRS WILL NOT have internet access beyond iAPI and LiteLLM, so all containers images MUST be able to run without internet access.
        # You MUST include your specific private CRS repo prefix so replace `ghcr.io/aixcc-sc/crs-sandbox` with `ghcr.io/aixcc-sc/crs-XXXXXXXX` or whatever
        # your private CRS repo is called but only for containers you are adding or those container images.

        # DO NOT add version labels here. That should be managed using the Github release process in your CRS repo.
        # Please see: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository


        include:
          - dockerfile: ./mock_crs/src/Dockerfile
            image: ghcr.io/aixcc-sc/${{ github.event.repository.name }}/mock_crs
    permissions:
      contents: write # to push chart release and create a release (helm/chart-releaser-action)
      packages: write # needed for ghcr access
      id-token: write # needed for keyless signing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Get the commit SHA for the tag
        id: get_tag_commit
        run: |
          TAG_COMMIT_SHA=$(git rev-list -n 1 ${{ github.event.release.tag_name }})
          echo "TAG_COMMIT_SHA=${TAG_COMMIT_SHA}" >> "$GITHUB_ENV"

      - name: Get the latest commit SHA from main branch
        id: get_main_commit
        run: |
          MAIN_COMMIT_SHA=$(git rev-parse origin/main)
          echo "MAIN_COMMIT_SHA=${MAIN_COMMIT_SHA}" >> "$GITHUB_ENV"

      - name: Check if tag commit is an ancestor of the main branch
        id: check_ancestor
        run: |
          if git merge-base --is-ancestor "${{ env.TAG_COMMIT_SHA }}" "${{ env.MAIN_COMMIT_SHA }}"; then
            echo "The release tag commit is an ancestor of the current main branch."
          else
            echo "The release tag commit is not an ancestor of the current main branch."
            exit 1
          fi
      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image. The `id` "meta" allows the output of this step to be referenced in a subsequent step. The `images` value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ matrix.image }}
      # This step uses the `docker/build-push-action` action to build the image, based on your repository's `Dockerfile`. If the build succeeds, it pushes the image to GitHub Packages.
      # It uses the `context` parameter to define the build's context as the set of files located in the specified path. For more information, see "[Usage](https://github.com/docker/build-push-action#usage)" in the README of the `docker/build-push-action` repository.
      # It uses the `tags` and `labels` parameters to tag and label the image with the output from the "meta" step.
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
